GRANT CONNECT ON DATABASE padel_manager TO app_user;
GRANT CONNECT ON DATABASE padel_manager TO app_readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO app_readonly;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;